<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class InventorySeeder extends Seeder
{
    public function run()
    {
        $inventoryItems = [
            [
                'branch_id' => 1,
                'item_name' => 'Rice Flour',
                'item_description' => 'Fine rice flour for making Chakli and Murukku',
                'unit' => 'kg',
                'quantity' => 500,
                'reorder_level' => 100,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Urad Flour',
                'item_description' => 'Split black gram flour for snack preparation',
                'unit' => 'kg',
                'quantity' => 300,
                'reorder_level' => 75,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Gram Flour',
                'item_description' => 'Chickpea flour for binding and thickening',
                'unit' => 'kg',
                'quantity' => 250,
                'reorder_level' => 50,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Refined Vegetable Oil',
                'item_description' => 'Oil for frying and roasting snacks',
                'unit' => 'liter',
                'quantity' => 800,
                'reorder_level' => 150,
                'expiry_date' => date('Y-m-d', strtotime('+6 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Salt (Refined)',
                'item_description' => 'Refined table salt for seasoning',
                'unit' => 'kg',
                'quantity' => 200,
                'reorder_level' => 40,
                'expiry_date' => date('Y-m-d', strtotime('+24 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Red Chili Powder',
                'item_description' => 'Spicy red chili powder for flavoring',
                'unit' => 'kg',
                'quantity' => 80,
                'reorder_level' => 15,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Turmeric Powder',
                'item_description' => 'Ground turmeric for color and health benefits',
                'unit' => 'kg',
                'quantity' => 60,
                'reorder_level' => 12,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Cumin Seeds',
                'item_description' => 'Whole cumin seeds for aromatic flavor',
                'unit' => 'kg',
                'quantity' => 50,
                'reorder_level' => 10,
                'expiry_date' => date('Y-m-d', strtotime('+18 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Sesame Seeds',
                'item_description' => 'White sesame seeds for coating and flavor',
                'unit' => 'kg',
                'quantity' => 40,
                'reorder_level' => 8,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Black Pepper',
                'item_description' => 'Ground black pepper for sharp spice flavor',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 5,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Asafoetida (Hing)',
                'item_description' => 'Aromatic resin for traditional flavor profile',
                'unit' => 'kg',
                'quantity' => 5,
                'reorder_level' => 1,
                'expiry_date' => date('Y-m-d', strtotime('+24 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Fenugreek Seeds',
                'item_description' => 'Methi seeds for authentic taste',
                'unit' => 'kg',
                'quantity' => 30,
                'reorder_level' => 6,
                'expiry_date' => date('Y-m-d', strtotime('+18 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Coriander Seeds',
                'item_description' => 'Aromatic coriander seeds for spice blend',
                'unit' => 'kg',
                'quantity' => 35,
                'reorder_level' => 7,
                'expiry_date' => date('Y-m-d', strtotime('+18 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Carom Seeds',
                'item_description' => 'Ajwain seeds for digestive and flavorful snacks',
                'unit' => 'kg',
                'quantity' => 20,
                'reorder_level' => 4,
                'expiry_date' => date('Y-m-d', strtotime('+18 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
            [
                'branch_id' => 1,
                'item_name' => 'Moong Dal (Split)',
                'item_description' => 'Roasted mung beans for snack preparation',
                'unit' => 'kg',
                'quantity' => 150,
                'reorder_level' => 30,
                'expiry_date' => date('Y-m-d', strtotime('+12 months')),
                'created_at' => Time::now(),
                'updated_at' => Time::now(),
            ],
        ];

        // Insert inventory items
        foreach ($inventoryItems as $item) {
            $this->db->table('inventory')->insert($item);
        }
    }
}
